name: codelab-cpp-actions
run-name: ${{ github.actor }} is testing cpp build and execution.
on: [push]
jobs:
  exercises_sams-teach-urself-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: cd exercises/sams-teach-urself-cpp ; for i in ./*.cpp ; do g++ $i.cpp -o $i.out && ./$.out ; done ; cd ../..
